
platform :ios, '8.0'

target 'JLSina' do
use_frameworks!

pod 'AFNetworking'
pod 'SDWebImage'
pod 'FMDB'
pod 'SVProgressHUD'
pod 'pop'
#pod 'SwiftyJSON’
pod 'YYModel'
#pod 'ObjectMapper'
#pod 'MJExtension'


end
